### ISSUE TITLE
PathSeparator() is undefined

### ISSUE THREAD

**Issue by DecimalTurn** [cristianbuse/VBA-FileTools#18]
On this line of the demo module, the function is undefined:

`subFolder = subFolder & i & PathSeparator()`

**Comment by DecimalTurn** [comment]
Also, on line 188, the demo module is calling a private function, so we get a compile error: 
`Debug.Print "UNC path is: " & GetUNCPath(filePath)`

**Comment by cristianbuse** [comment]
Thanks @DecimalTurn ,

Thanks for raising the issues. I just fixed them.

Unfortunately, I've been quite busy in the last few months and besides updating this repo for SQLite, I haven't spent the proper time to do all the work that needs to be done. There are quite a few functions that need to be updated for Mac and I intend to do many other changes including to completely rewrite the demo module and start a proper documentation plus testing. Hopefully next year.

Thanks again!

**Comment by DecimalTurn** [comment]
My pleasure, thanks for putting this out there, it's already a good resource!

Just curious, what is the benefit of using the constant PATH_SEPARATOR (via conditional compilation) versus using `Application.PathSeparator`? My understanding was that `Application.PathSeparator` is preferable because it can return ":" for Classic Mac OS, but maybe that's too ancient for being worth addressing.

**Comment by DecimalTurn** [comment]
Ah, I didn't know Application.PathSeparator isn't available for Outlook before looking it up [here](https://stackoverflow.com/questions/33573948/outlook-vba-pathseparator-property-missing-in-application-object). Good to know and I'm assuming AutoCAD doesn't have it either. 

Regarding not supporting Classic Mac OS, it's propably the right call, I just wanted to make sure that it was intentional as it's not mentioned elsewhere in the project.
