### ISSUE TITLE
Cannot compile in office 365

### ISSUE THREAD

**Issue by itsdalien** [cristianbuse/VBA-FileTools#25]
**Describe the bug**
Cannot compile in office 365. Errors due to Mac related code 

**To Reproduce**
1. Compile

**Expected behavior**
Complies

**Screenshots**
Not applicable 

**Version (please complete the following information):**
 - OS: [win10]
 - VBA Version [latest office 365 vba7)
 - Bitness [x64]

**Additional context**
Not applicable

**Comment by cristianbuse** [comment]
Hi @itsdalien ,

Please download the [zip](https://github.com/cristianbuse/VBA-FileTools/archive/refs/heads/master.zip), extract and then import the ```LibFileTools``` module via the VBE interface. There should be no compilation issue.

**Comment by cristianbuse** [comment]
Could you please try to import the module in a different application, like Microsoft Word, and in a new document? I'm just wondering if your issue is related to your specific project or just clashing with one of your Excel add-ins.
