### ISSUE TITLE
Local/Remote Path Conversion Bug

### ISSUE THREAD

**Issue by YDEdi** [cristianbuse/VBA-FileTools#32]
tests :
GetLocalPath("https://cloud") -> "C:\synccloud" - ok
GetLocalPath("c:\test") -> "C:\test" (why?) - ok
GetLocalPath("\\machine\path") -> Empty - KO ?

**Comment by cristianbuse** [comment]
@YDEdi Not sure what ```GetLocalPath("\machine\path")``` means. Can you please provide an example?

**Comment by YDEdi** [comment]
if we work on a samba path "\\\machine\path", the path must be recognized by the GetLocalPath function

**Comment by cristianbuse** [comment]
as far as I know this already works when you are using mapped network drives. For example, ```GetLocalPath("\\emea.cbre.net\a\b\c")``` correctly returns ```X:\" for me.

**Comment by cristianbuse** [comment]
@YDEdi Any updates on this? Is it still not working? If not, then can you provide me with more details?

**Comment by YDEdi** [comment]
Of course I'm testing on an unmapped share.
In a hurry, I hadn't reacted on the returnInputOnFail argument

**Comment by cristianbuse** [comment]
Thanks for the feedback!
