### ISSUE TITLE
Windows file/folder reserved names: aux

### ISSUE THREAD

**Issue by john-tvh** [cristianbuse/VBA-FileTools#4]
Hi Cristian, I was checking out your excellent LibFileTools. I believe the list of Windows file/folder reserved names in the `IsReservedName` Function is missing one reserved name, that being "aux".

This per https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

Testing on my Windows 10 device shows this filename is not allowed.

**Comment by cristianbuse** [comment]
Hi John, thank you for raising the issue and for the kind words! I've added the missing name.
