### ISSUE TITLE
"Invalid procedure call or argument (Error 5)" raised when calling GetLocalPath

### ISSUE THREAD

**Issue by fdelaine** [cristianbuse/VBA-FileTools#5]
Hi,

I ran into your library while looking for a solution to get local file paths when shared between users across OneDrive or Sharepoint. Thanks for your work on this subject, I've been looking for a solution since months!

I encountered a bug when running GetLocalPath. An "Invalid procedure call or argument (Error 5)" is raised and issue occurs at line 1096 of the lib (https://github.com/cristianbuse/VBA-FileTools/blob/master/src/LibFileTools.bas#L1096).

I just imported the module in a new workbook and called the function from a macro.

Note that the standalone function given on StackOverflow works properly (https://stackoverflow.com/questions/33734706/excels-fullname-property-with-onedrive/73577057#73577057).

I have not digged into the issue yet. I'll give more context if necessary.

Regards,

**Comment by cristianbuse** [comment]
Thanks @fdelaine 

I missed the case where there is no Personal OneDrive. All I had to do was to swap the 4th line of that ```Do``` loop to be the first. Just pushed an update.
